const truthQuestions = [
"What was your first impression of me?",
"What is something you've always wanted to tell me but haven't yet?",
"What do you love most about our relationship?",
"What is a dream or goal you have for our future together?",
"What’s the most memorable moment we’ve shared so far?",
"What are three things you admire about me?",
"What’s something you think we could improve in our relationship?",
"What was the moment you knew you were in love with me?",
"Have you ever had a dream about me? If so, what was it about?",
"What’s your favorite way we spend time together?",
"What’s something you’ve always wanted to do as a couple but haven't yet?",
"What’s a fear you have about our relationship?",
"What do you think is your biggest strength in our relationship?",
"How do you feel about our communication?",
"What’s the best compliment you’ve ever received from me?",        
"vWhat is your favorite thing to do with me?", 
"If you could change one thing about our relationship, what would it be?",
"What do you think our relationship will look like in five years?",
"What’s the most important lesson you've learned from our relationship?",
"Is there something you’ve always wanted to ask me but never did?",
"How do you feel when we're apart for a long time?",
"What is your favorite physical feature of mine?",
"What’s a funny moment we’ve shared that still makes you laugh?",
"How do you describe me to your friends and family?",
"What’s one thing you want us to experience together?",
"What’s the nicest thing you’ve done for me?",
"What’s your favorite thing that I do for you?",
"What’s a bad habit you have that you think I should know about?",
"What’s one thing you’ve learned about relationships from your parents?",
"If we could travel anywhere in the world together, where would it be and why?",
"What do you think is my best quality?",
"What is the most romantic thing I’ve ever done for you?",
"Have you ever had a dream about our future together? What was it about?",
"What’s a challenge we’ve faced together that made us stronger?",
"What do you think we have in common that helps our relationship?",
"How have you grown as a person since we’ve been together?",
"What’s something you wish we did more often?",
"What’s the best gift you’ve ever received from me?",
"How do you feel about the way we resolve conflicts?",
"What’s a talent or skill you have that you think I don’t know about?",
"What’s a hobby or interest you’d like us to try together?",
"What’s one thing you think I don’t appreciate enough about myself?",
"What’s a book or movie that you think represents our relationship?",
"If we could live anywhere in the world, where would you choose and why?",
"What’s one piece of advice you would give to other couples?",
"What’s the most thoughtful thing I’ve ever done for you?",
"What’s a memory of us that always makes you smile?",
"How would you describe our relationship in three words?",
"What’s one thing you’d like to change about yourself for the sake of our relationship?",
"What’s your favorite nickname or pet name that I call you?",
"How do you feel when we are apart?",
"What’s one thing you think we should do more as a couple?",
"What’s a quality you’ve admired in me but never told me about?",
"What’s a funny or embarrassing moment we’ve shared that you’ll never forget?",
"How do you feel about our future together?",
"What’s your favorite way for us to spend a day off together?",
"What’s a new tradition you’d like to start with me?",
"What’s the best adventure we’ve had together so far?",
"How do you think we complement each other as partners?",
"What’s one thing you’d like to learn about me that you don’t already know?",
"How do you think we complement each other as partners?",
"What’s the most romantic thing you can imagine us doing together?",
"What’s one habit of mine that you find endearing?",
"What’s something new you’ve learned about yourself since we started dating?",
"What do you think makes us a great team?",
"What’s a quality in me that you wish you had?",
"What’s your favorite way I show you that I love you?",
"What’s a challenge you’ve faced that you’re proud of overcoming with my support?",
"What’s the funniest thing that’s ever happened to us?",
"What’s one thing you’ve always wanted to try but have been too scared to?",
"What’s a movie or TV show that reminds you of our relationship?",
"What’s your favorite physical activity to do together?",
"What’s one way you think we can better support each other’s goals?",
"How do you feel when you see me after we’ve been apart?",
"What’s your favorite memory of us from this past year?",
"What’s something about our relationship that makes you feel proud?",
"What’s a song that always reminds you of me?",
"What’s something you’ve always wanted to ask me but were too afraid to?",
"What’s a place you’ve always wanted to visit with me?",
"What’s your favorite compliment I’ve ever given you?",
"What’s one of your biggest dreams for our future?",
"What do you think our biggest strength as a couple is?",
"What’s your favorite way to be comforted when you’re upset?",
"What’s a lesson you’ve learned from our relationship?",
"How do you like to spend your free time when we’re together?",
"What’s a moment when you felt proud of us as a couple?",
"What’s a small thing I do that always makes you smile?",
"What’s one thing you want to achieve together in the next year?",
"What’s your favorite thing about our communication?",
"What’s a tradition you’d like to start with me?",
"What’s a favorite memory of us from the last month?",
    // Add more truth questions here
];

const dareQuestions = [
"Write a love letter to each other and read it aloud.",
"Give each other a 5-minute back massage.",
"Share your favorite romantic memory together.",
"Look into each other’s eyes for one minute without saying anything.",
"Share a song that reminds you of your partner and explain why.",
"Dance together to your favorite song.",
"Take a cute couple selfie and make it your profile picture for a day.",
"Give each other a genuine compliment every day for a week.",
"Cook a meal together and feed each other.",
"Share your most embarrassing moment with each other.",
"Plan a surprise date for your partner.",
"Sing a love song to your partner.",
"Exchange an item of clothing and wear it for the rest of the game.",
"Recreate your first date.",
"Create a scrapbook page of your favorite memories together.",
"Write a poem for each other and read it aloud.",
"Give each other a forehead kiss and say something sweet.",
"Share a secret fantasy with each other.",
"Make a list of 5 things you love about each other and share it.",
"Take turns saying something you’re grateful for in your relationship.",
"Do an impression of each other.",
"Give each other a pet name for the rest of the day.",
"Plan your next vacation together.",
"Create a vision board for your future together.",
"Make a playlist of songs that remind you of each other.",
"Build a fort and watch a movie inside it.",
"Act out a scene from your favorite romantic movie.",
"Describe your partner using only your hands (no words).",
"Share a story about your childhood that your partner doesn’t know.",
"Spend 10 minutes just holding each other without speaking.",
"Make a short video together talking about your relationship.",
"Give each other a piggyback ride.",
"Spend five minutes drawing each other.",
"Tell each other your favorite joke and laugh together.",
"Do a silly dance together without music.",
"Recreate a photo of the two of you from when you first started dating.",
"Describe your partner’s best features while blindfolded.",
"Make a bucket list of things you want to do together.",
"Give each other a foot massage.",
"Take turns feeding each other something sweet.",
"Do a random act of kindness together for someone else.",
"Plan a themed date night (e.g., Italian, 80s, beach).",
"Write a haiku about each other.",
"Watch a sunrise or sunset together and talk about your future.",
"Spend 10 minutes talking only in whispers.",
"Exchange shirts and take a selfie together.",
"Write and perform a short song about your relationship.",
"Plan a surprise date for each other within the next week.",
"Blindfold one person and have them guess what objects they are touching.",
"Create a personalized handshake.",
"Act out a favorite scene from a romantic movie without using words.",
"Take a funny video together and share it with a friend or family member.",
"Spend five minutes telling each other what you love most about the other person.",
"Try to recreate your first kiss.",
"Spend the next 10 minutes speaking in a foreign accent.",
"Draw a portrait of each other with your non-dominant hand.",
"Make a fort out of blankets and spend time inside it talking about your dreams.",
"Play a song that means a lot to your relationship and slow dance to it.",
"Read each other’s favorite poem or passage from a book.",
"Give each other a new hairstyle.",
"Create a piece of art together (e.g., painting, drawing, sculpture).",
"Write down your favorite memory of each other and share it.",
"Make up a secret handshake that only the two of you know.",
"Give each other a nickname that you have to use for the rest of the day.",
"Go outside and stargaze together while talking about your future.",
"Describe your favorite qualities of your partner as if you were introducing them to someone new.",
"Make each other breakfast in bed tomorrow morning.",
"Write down five things you appreciate about each other and read them aloud.",
"Create a list of 10 things you want to do together this year.",
"Take turns saying sweet things about each other for five minutes.",
"Pretend you are meeting each other for the first time and act out the scene.",
"Set up a mini indoor picnic and enjoy it together.",
"Try a new hobby or activity together that neither of you has done before.",
"Plan and prepare a fancy dinner together at home.",
"Spend a minute staring into each other’s eyes without talking, then share how it felt.",
"Write a list of reasons why you love each other and exchange them.",
"Make a dessert together and feed each other.",
"Recreate a favorite photo of yourselves from the past.",
"Plan a spontaneous mini-adventure together.",
"Create a secret code or language that only the two of you understand.",
"Write a short story together, each taking turns to write one sentence at a time.",
"Spend an evening looking through old photos and reminiscing.",
"Give each other a silly makeover.",
"Plan and execute a random act of kindness together.",
"Describe each other using only positive adjectives.",
"Write a bucket list of things you want to do together in the next five years.",
"Try to guess each other’s favorite movie scenes and act them out.",
"Create a mini time capsule with items that represent your relationship and bury it together.",
"Spend the next 10 minutes asking each other any questions that come to mind.",
"Build something together, like a small piece of furniture or a craft project.",
    // Add more dare questions here
];

const relationshipQuotes = [
    "Love is composed of a single soul inhabiting two bodies. - Aristotle",
    "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves. - Victor Hugo",
    "A successful marriage requires falling in love many times, always with the same person. - Mignon McLaughlin",
    "You are my sunshine on a cloudy day.",
    "In your arms, I find my home.",
    "Every moment with you is a treasure.",
    "Your love is the melody to my heart's song.",
    "I am yours, and you are mine, forever.",
    "With you, I feel complete.",
"You are the light that guides me through the darkest nights.",
"I love you more than words can express.",
"You are the reason I believe in love.",
"Your smile brightens my world.",
"In your embrace, I find peace.",
"Loving you is the best decision I've ever made.",
"My heart belongs to you, now and always.",
"With you, I've found my happily ever after.",
"You are my soulmate, my partner in life's journey.",
"I am grateful for every moment we share together.",
"Your love is my greatest blessing.",
"With you by my side, I can conquer anything.",
"You are the missing piece of my puzzle.",
"Your love is the anchor that keeps me grounded.",
"I fall for you more and more each day.",
"You are the love of my life.",
"My love for you knows no bounds.",
"You make my heart skip a beat.",
"With you, I've found my forever.",
"Your love is my greatest strength.",
"I cherish every memory we've created together.",
"You are the love story I've always dreamed of.",
"With you, I've found true happiness.",
"You are the epitome of beauty, inside and out.",
"I love you to the moon and back.",
"Your love is my North Star, guiding me home.",
"You are the best thing that's ever happened to me.",
"With you, I am the best version of myself.",
"You are my everything.",
"Your love is my greatest adventure.",
"With you, I've found my forever home.",
"I am forever grateful for your love.",
"You are the love I've been searching for my whole life.",
"You are the answer to all my prayers.",
"I am blessed to have you in my life.",
"With you, I've found my soul's counterpart.",
"Your love is my safe haven.",
"You are the greatest gift I've ever received.",
"I love you more than yesterday, but less than tomorrow.",
"With you, every day is Valentine's Day.",
"You are the reason I believe in happily ever after.",
"Your love fills my heart with joy.",
"You are my forever and always.",
"I love you beyond measure.",
    // Add more relationship quotes here
];

function getRandomElement(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function getTruth() {
    const questionContainer = document.getElementById("question");
    const question = getRandomElement(truthQuestions);
    questionContainer.textContent = question;
}

function getDare() {
    const questionContainer = document.getElementById("question");
    const question = getRandomElement(dareQuestions);
    questionContainer.textContent = question;
}

function getQuote() {
    const quoteContainer = document.getElementById("quote");
    const quote = getRandomElement(relationshipQuotes);
    quoteContainer.textContent = quote;
}
